#!/usr/bin/env python3
"""Build Bayer SR tile pairs directly from existing low/high raw directories.

This is for guarded CNN iterations where the low input has already been
generated by a specific codec/profile. It preserves that provenance instead of
rerunning downsample or codec generation.
"""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any

import numpy as np


SCHEMA = "mission1_sr_pairs_from_raw_dirs.v1"


def read_u16_raw(path: Path, width: int, height: int) -> np.ndarray:
    arr = np.fromfile(path, dtype="<u2")
    expected = width * height
    if arr.size != expected:
        raise ValueError(f"{path} has {arr.size} pixels, expected {expected} for {width}x{height}")
    return arr.reshape((height, width))


def deinterleave(bayer: np.ndarray) -> np.ndarray:
    return np.stack(
        [
            bayer[0::2, 0::2],
            bayer[0::2, 1::2],
            bayer[1::2, 0::2],
            bayer[1::2, 1::2],
        ],
        axis=0,
    )


def load_tile_manifest(path: Path | None, low_tile: int, repeat: int) -> dict[str, list[dict[str, Any]]]:
    if path is None:
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    tiles = payload.get("tiles")
    if not isinstance(tiles, list):
        raise ValueError(f"{path} does not contain a tiles list")
    by_image: dict[str, list[dict[str, Any]]] = {}
    for tile in tiles:
        if not isinstance(tile, dict):
            raise ValueError(f"{path} contains a non-object tile")
        image_id = str(tile.get("image_id", ""))
        if not image_id:
            raise ValueError(f"{path} contains a tile without image_id")
        tile_low = int(tile.get("low_tile", low_tile))
        if tile_low != low_tile:
            raise ValueError(f"{path} tile for {image_id} has low_tile={tile_low}, expected {low_tile}")
        row = {
            "image_id": image_id,
            "low_x": int(tile["low_x"]),
            "low_y": int(tile["low_y"]),
            "low_tile": low_tile,
            "sample_source": "tile_manifest",
            "tile_manifest": str(path),
        }
        for key in ("score", "rank", "score_mode", "source_compare", "score_components"):
            if key in tile:
                row[key] = tile[key]
        by_image.setdefault(image_id, []).extend(dict(row) for _ in range(max(1, repeat)))
    return by_image


def common_stems(low_dir: Path, target_dir: Path, stems: list[str] | None) -> list[str]:
    if stems:
        selected = sorted(set(stems))
    else:
        selected = sorted({p.stem for p in low_dir.glob("*.raw")} & {p.stem for p in target_dir.glob("*.raw")})
    if not selected:
        raise ValueError(f"no common .raw stems found in {low_dir} and {target_dir}")
    return selected


def sample_one(
    *,
    low_planes: np.ndarray,
    high_planes: np.ndarray,
    image_id: str,
    low_tile: int,
    tiles_per_image: int,
    prescribed_tiles: list[dict[str, Any]],
    manifest_only: bool,
    rng: random.Random,
) -> tuple[list[np.ndarray], list[np.ndarray], list[dict[str, Any]]]:
    _, low_h, low_w = low_planes.shape
    high_tile = low_tile * 2
    xs: list[np.ndarray] = []
    ys: list[np.ndarray] = []
    rows: list[dict[str, Any]] = []

    def append_tile(x: int, y: int, row: dict[str, Any]) -> None:
        if x < 0 or y < 0 or x + low_tile > low_w or y + low_tile > low_h:
            raise ValueError(f"tile for {image_id} out of bounds: x={x} y={y} low_tile={low_tile}")
        xs.append(low_planes[:, y : y + low_tile, x : x + low_tile])
        ys.append(high_planes[:, y * 2 : y * 2 + high_tile, x * 2 : x * 2 + high_tile])
        out = dict(row)
        out.update({"image_id": image_id, "low_x": x, "low_y": y, "low_tile": low_tile})
        rows.append(out)

    for tile in prescribed_tiles:
        append_tile(int(tile["low_x"]), int(tile["low_y"]), tile)

    if not manifest_only:
        for _ in range(tiles_per_image):
            x = rng.randrange(0, low_w - low_tile + 1)
            y = rng.randrange(0, low_h - low_tile + 1)
            append_tile(x, y, {"sample_source": "random"})

    if not xs:
        raise ValueError(f"no tiles selected for {image_id}")
    return xs, ys, rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--low-dir", type=Path, required=True)
    ap.add_argument("--target-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--low-width", type=int, required=True)
    ap.add_argument("--low-height", type=int, required=True)
    ap.add_argument("--high-width", type=int, required=True)
    ap.add_argument("--high-height", type=int, required=True)
    ap.add_argument("--low-clean-dir", type=Path)
    ap.add_argument("--stem", action="append")
    ap.add_argument("--tiles-per-image", type=int, default=96)
    ap.add_argument("--low-tile", type=int, default=96)
    ap.add_argument("--tile-manifest", type=Path)
    ap.add_argument("--manifest-only", action="store_true")
    ap.add_argument("--manifest-repeat", type=int, default=1)
    ap.add_argument("--dataset-label", default="raw_dir_pairs")
    ap.add_argument("--seed", type=int, default=20260624)
    args = ap.parse_args()

    if args.low_width * 2 != args.high_width or args.low_height * 2 != args.high_height:
        raise ValueError("high dimensions must be exactly 2x low dimensions")
    if args.low_width % 2 or args.low_height % 2 or args.high_width % 2 or args.high_height % 2:
        raise ValueError("Bayer dimensions must be even")

    manifest_tiles = load_tile_manifest(args.tile_manifest, args.low_tile, args.manifest_repeat)
    stems = common_stems(args.low_dir, args.target_dir, args.stem)
    rng = random.Random(args.seed)

    all_x: list[np.ndarray] = []
    all_y: list[np.ndarray] = []
    tile_rows: list[dict[str, Any]] = []
    image_rows: list[dict[str, Any]] = []

    for stem in stems:
        low_path = args.low_dir / f"{stem}.raw"
        target_path = args.target_dir / f"{stem}.raw"
        low_clean_path = args.low_clean_dir / f"{stem}.raw" if args.low_clean_dir else None
        low = deinterleave(read_u16_raw(low_path, args.low_width, args.low_height))
        high = deinterleave(read_u16_raw(target_path, args.high_width, args.high_height))
        xs, ys, rows = sample_one(
            low_planes=low,
            high_planes=high,
            image_id=stem,
            low_tile=args.low_tile,
            tiles_per_image=args.tiles_per_image,
            prescribed_tiles=manifest_tiles.get(stem, []),
            manifest_only=args.manifest_only,
            rng=rng,
        )
        all_x.extend(xs)
        all_y.extend(ys)
        tile_rows.extend(rows)
        image_rows.append(
            {
                "image_id": stem,
                "low_source_raw": str(low_path),
                "high_target_raw": str(target_path),
                "low_clean_raw": str(low_clean_path) if low_clean_path and low_clean_path.exists() else None,
                "low_width": args.low_width,
                "low_height": args.low_height,
                "high_width": args.high_width,
                "high_height": args.high_height,
                "dataset_label": args.dataset_label,
            }
        )

    inputs = np.stack(all_x).astype(np.uint16)
    targets = np.stack(all_y).astype(np.uint16)
    meta = {
        "schema": SCHEMA,
        "source": "existing low/high Bayer raw directories",
        "dataset_label": args.dataset_label,
        "low_dir": str(args.low_dir),
        "target_dir": str(args.target_dir),
        "low_clean_dir": str(args.low_clean_dir) if args.low_clean_dir else None,
        "low_width": args.low_width,
        "low_height": args.low_height,
        "high_width": args.high_width,
        "high_height": args.high_height,
        "low_tile": args.low_tile,
        "high_tile": args.low_tile * 2,
        "tiles_per_image": args.tiles_per_image,
        "tile_manifest": str(args.tile_manifest) if args.tile_manifest else None,
        "manifest_only": bool(args.manifest_only),
        "manifest_repeat": int(args.manifest_repeat),
        "seed": args.seed,
        "images": image_rows,
        "tiles": tile_rows,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.out, inputs=inputs, targets=targets, meta=json.dumps(meta))
    args.out.with_suffix(args.out.suffix + ".json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(json.dumps({"out": str(args.out), "inputs": list(inputs.shape), "targets": list(targets.shape)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
