#!/bin/bash
# Post-flash configuration for the Pi 5 SD card.
# Run on Mac AFTER `dd if=raspios.img of=/dev/rdiskN bs=4m` finishes and the
# card auto-remounts. Creates a firstrun.sh that the freshly-flashed Pi OS
# will execute on first boot: sets hostname, renames default user to
# dcliftreaves, installs SSH pubkey, enables SSH service.
#
# Config:
#   hostname:  gpr-pi
#   user:      dcliftreaves (pubkey-only auth, no password)
#   network:   Ethernet only (no WiFi)
#   ssh pubkey: ~/.ssh/id_ed25519.pub
#
# Usage:
#   bash tools/test/configure_pi_sd.sh
set -euo pipefail

BOOTFS="${BOOTFS:-/Volumes/bootfs}"
HOSTNAME="${MISSION1_HOSTNAME:-gpr-pi}"
USERNAME="${MISSION1_USERNAME:-dcliftreaves}"
PUBKEY_FILE="${MISSION1_PUBKEY_FILE:-$HOME/.ssh/id_ed25519.pub}"

# Sanity
if [ ! -d "$BOOTFS" ]; then
    echo "ERROR: $BOOTFS not mounted. Re-insert the SD card or wait for automount."
    exit 1
fi
if [ ! -f "$BOOTFS/cmdline.txt" ]; then
    echo "ERROR: $BOOTFS doesn't look like a freshly-flashed Pi OS bootfs (missing cmdline.txt)."
    exit 2
fi
if [ ! -f "$PUBKEY_FILE" ]; then
    echo "ERROR: pubkey $PUBKEY_FILE not found."
    exit 3
fi

PUBKEY=$(cat "$PUBKEY_FILE")
echo "Configuring bootfs at $BOOTFS"
echo "  hostname: $HOSTNAME"
echo "  user:     $USERNAME"
echo "  pubkey:   ${PUBKEY:0:50}..."

# 1. Enable SSH at boot
touch "$BOOTFS/ssh"

# 2. Write firstrun.sh
# Imager-format script — Pi OS recognizes this path + cmdline.txt hook.
cat > "$BOOTFS/firstrun.sh" <<EOF
#!/bin/bash
# Generated by configure_pi_sd.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
set +e

# Hostname
CURRENT_HOSTNAME=\$(cat /etc/hostname | tr -d ' \\t\\n\\r')
if [ -f /usr/lib/raspberrypi-sys-mods/imager_custom ]; then
    /usr/lib/raspberrypi-sys-mods/imager_custom set_hostname $HOSTNAME
else
    echo "$HOSTNAME" > /etc/hostname
    sed -i "s/127.0.1.1.*\$CURRENT_HOSTNAME/127.0.1.1\\t$HOSTNAME/g" /etc/hosts
fi

# User: rename default 'pi' (uid 1000) to '$USERNAME'
FIRSTUSER=\$(getent passwd 1000 | cut -d: -f1)
FIRSTUSERHOME=\$(getent passwd 1000 | cut -d: -f6)
if [ -f /usr/lib/userconf-pi/userconf ]; then
    /usr/lib/userconf-pi/userconf '$USERNAME' '*'
else
    if [ "\$FIRSTUSER" != "$USERNAME" ]; then
        usermod -l "$USERNAME" "\$FIRSTUSER"
        usermod -m -d "/home/$USERNAME" "$USERNAME"
        groupmod -n "$USERNAME" "\$FIRSTUSER"
        if grep -q "^autologin-user=" /etc/lightdm/lightdm.conf 2>/dev/null; then
            sed -i "/^autologin-user=/c\\autologin-user=$USERNAME" /etc/lightdm/lightdm.conf
        fi
        if [ -f /etc/systemd/system/getty@tty1.service.d/autologin.conf ]; then
            sed -i "s/--autologin \$FIRSTUSER/--autologin $USERNAME/g" /etc/systemd/system/getty@tty1.service.d/autologin.conf
        fi
        if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
            sed -i "s/^\$FIRSTUSER /$USERNAME /" /etc/sudoers.d/010_pi-nopasswd
        fi
    fi
fi
# Lock the user (no password — pubkey only)
passwd -l "$USERNAME"

# Install SSH pubkey
install -o "$USERNAME" -g "$USERNAME" -m 0700 -d "/home/$USERNAME/.ssh"
cat > "/home/$USERNAME/.ssh/authorized_keys" <<KEYEOF
$PUBKEY
KEYEOF
chown "$USERNAME:$USERNAME" "/home/$USERNAME/.ssh/authorized_keys"
chmod 0600 "/home/$USERNAME/.ssh/authorized_keys"

# Enable SSH
systemctl enable ssh
systemctl start ssh

# Set timezone
/usr/bin/timedatectl set-timezone "America/Chicago" || true
# Set keymap
/usr/bin/raspi-config nonint do_configure_keyboard "us" || true

# Self-cleanup: remove the script and the cmdline hook
rm -f /boot/firmware/firstrun.sh
sed -i 's| systemd.run.*||g' /boot/firmware/cmdline.txt
exit 0
EOF
chmod +x "$BOOTFS/firstrun.sh"

# 3. Hook cmdline.txt to run firstrun.sh on first boot
CMDLINE=$(cat "$BOOTFS/cmdline.txt")
if ! grep -q "systemd.run" "$BOOTFS/cmdline.txt"; then
    # Append the systemd.run hook on the same line (cmdline.txt is one line)
    HOOK=" systemd.run=/boot/firmware/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target"
    # Strip trailing newline first
    printf '%s%s\n' "$(cat "$BOOTFS/cmdline.txt" | tr -d '\n')" "$HOOK" > "$BOOTFS/cmdline.txt"
    echo "  hooked firstrun.sh into cmdline.txt"
else
    echo "  cmdline.txt already has a systemd.run hook — not modifying"
fi

echo ""
echo "DONE. SD card configured."
echo "  bootfs contents:"
ls -la "$BOOTFS" | grep -E "ssh|firstrun|cmdline" | head -5
echo ""
echo "Eject the card:"
echo "  diskutil eject \$(diskutil list | grep -B1 'bootfs' | head -1 | awk '{print \$1}')"
echo "Then put it in the Pi and power on. The Pi will:"
echo "  1. Boot from SD"
echo "  2. Run firstrun.sh (set hostname, install pubkey, enable SSH)"
echo "  3. Reboot"
echo "  4. Come up with ssh ready. Test:  ssh gpr-pi 'hostname && uname -a'"
echo ""
echo "If hostname doesn't resolve, find IP via your router and update ~/.ssh/config."
